language: node_js

node_js:
  - "8"

install:
 - npm install

script:
 - npm test

# branches:
#   except:
#   - develop

after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - export REPO=frojd/hastur
 - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH#?} ; fi`
 - docker build . -t $REPO:$TAG
 - docker push $REPO