language: node_js

node_js:
  - "8"

install:
 - npm install

script:
 - npm test

after_success:
 - export REPO=frojd/hastur
 - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH#?} ; fi`
 - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASS;
      docker build . -t $REPO:$TAG;
      docker push $REPO;
   fi